name: flutter_node_worker
description: A package for using Web Workers written in Node.js with Dart in Flutter web.
version: 0.0.1
homepage: https://github.com/printHelloworldd/flutter-node-worker
issue_tracker: https://github.com/printHelloworldd/flutter-node-worker/issues
documentation: https://github.com/printHelloworldd/flutter-node-worker/blob/main/README.md

platforms:
  web:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  cli_util: ^0.4.2
  args: ^2.7.0
  mustache_template: ^2.0.0
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

executables:
  fnw: flutter_node_worker

flutter:

  assets:
    - templates/

topics:
  - cli
  - web
  - isolate
  - worker
